import { DeckCard } from './types';
import { shuffle } from './utils';

export function buildDeck(): DeckCard[] {
  const deck: DeckCard[] = [
    { type: 'missed', suit: 'spades', value: 2 }, { type: 'missed', suit: 'spades', value: 3 },
    { type: 'missed', suit: 'spades', value: 4 }, { type: 'missed', suit: 'spades', value: 5 },
    { type: 'missed', suit: 'spades', value: 6 }, { type: 'missed', suit: 'spades', value: 7 },
    { type: 'missed', suit: 'spades', value: 8 }, { type: 'missed', suit: 'clubs', value: 14 },
    { type: 'missed', suit: 'clubs', value: 10 }, { type: 'missed', suit: 'clubs', value: 12 },
    { type: 'missed', suit: 'clubs', value: 11 }, { type: 'missed', suit: 'clubs', value: 13 },
    { type: 'general_store', suit: 'spades', value: 12 }, { type: 'general_store', suit: 'clubs', value: 9 },
    { type: 'cat_balou', suit: 'hearts', value: 13 }, { type: 'cat_balou', suit: 'diamonds', value: 9 },
    { type: 'cat_balou', suit: 'diamonds', value: 10 }, { type: 'cat_balou', suit: 'diamonds', value: 11 },
    { type: 'beer', suit: 'hearts', value: 6 }, { type: 'beer', suit: 'hearts', value: 7 },
    { type: 'beer', suit: 'hearts', value: 8 }, { type: 'beer', suit: 'hearts', value: 9 },
    { type: 'beer', suit: 'hearts', value: 10 }, { type: 'beer', suit: 'hearts', value: 11 },
    { type: 'gatling', suit: 'hearts', value: 10 },
    { type: 'saloon', suit: 'hearts', value: 5 },
    { type: 'stagecoach', suit: 'hearts', value: 3 },
    { type: 'wells_fargo', suit: 'spades', value: 9 }, { type: 'wells_fargo', suit: 'spades', value: 9 },
    { type: 'duel', suit: 'diamonds', value: 12 }, { type: 'duel', suit: 'spades', value: 11 }, { type: 'duel', suit: 'clubs', value: 8 },
    { type: 'indians', suit: 'diamonds', value: 14 }, { type: 'indians', suit: 'diamonds', value: 13 },
    { type: 'panic', suit: 'hearts', value: 14 }, { type: 'panic', suit: 'hearts', value: 11 },
    { type: 'panic', suit: 'hearts', value: 12 }, { type: 'panic', suit: 'diamonds', value: 8 },
    { type: 'bang', suit: 'spades', value: 14 }, { type: 'bang', suit: 'hearts', value: 14 },
    { type: 'bang', suit: 'hearts', value: 12 }, { type: 'bang', suit: 'hearts', value: 13 },
    { type: 'bang', suit: 'clubs', value: 2 }, { type: 'bang', suit: 'clubs', value: 3 },
    { type: 'bang', suit: 'clubs', value: 4 }, { type: 'bang', suit: 'clubs', value: 5 },
    { type: 'bang', suit: 'clubs', value: 6 }, { type: 'bang', suit: 'clubs', value: 7 },
    { type: 'bang', suit: 'clubs', value: 8 }, { type: 'bang', suit: 'clubs', value: 9 },
    { type: 'bang', suit: 'diamonds', value: 2 }, { type: 'bang', suit: 'diamonds', value: 3 },
    { type: 'bang', suit: 'diamonds', value: 4 }, { type: 'bang', suit: 'diamonds', value: 5 },
    { type: 'bang', suit: 'diamonds', value: 6 }, { type: 'bang', suit: 'diamonds', value: 7 },
    { type: 'bang', suit: 'diamonds', value: 8 }, { type: 'bang', suit: 'diamonds', value: 9 },
    { type: 'bang', suit: 'diamonds', value: 10 }, { type: 'bang', suit: 'diamonds', value: 11 },
    { type: 'bang', suit: 'diamonds', value: 12 }, { type: 'bang', suit: 'diamonds', value: 13 },
    { type: 'bang', suit: 'diamonds', value: 14 },
    { type: 'dynamite', suit: 'hearts', value: 2 },
    { type: 'prison', suit: 'hearts', value: 4 }, { type: 'prison', suit: 'spades', value: 11 }, { type: 'prison', suit: 'spades', value: 10 },
    { type: 'scope', suit: 'spades', value: 14 },
    { type: 'mustang', suit: 'hearts', value: 8 }, { type: 'mustang', suit: 'hearts', value: 9 },
    { type: 'barrel', suit: 'spades', value: 13 }, { type: 'barrel', suit: 'spades', value: 12 },
    { type: 'winchester', suit: 'spades', value: 8 },
    { type: 'carbine', suit: 'clubs', value: 14 },
    { type: 'remington', suit: 'clubs', value: 13 },
    { type: 'schofield', suit: 'spades', value: 13 }, { type: 'schofield', suit: 'clubs', value: 11 }, { type: 'schofield', suit: 'clubs', value: 12 },
    { type: 'volcanic', suit: 'spades', value: 10 }, { type: 'volcanic', suit: 'clubs', value: 10 },
  ];
  return shuffle(deck);
}